---
train:
    moving_average_decay: 0.9999
    learning_rate:
        type: tensorflow.train.exponential_decay
        _initial: 0.1
        _num_epochs_per_decay: 350
        decay_rate: 0.1
        learning_rate: !arith >
            $(train.learning_rate._initial) *
            math.sqrt($(system.batch_size) / 128)
        decay_steps: !arith >
            $(dataset.num_examples_per_epoch.train) / $(system.batch_size) *
            $(train.learning_rate._num_epochs_per_decay)
        staircase: true
    optimizer:
        type: tensorflow.train.GradientDescentOptimizer
