---
train:
    max_steps: 10000000
    batch_size: 64
    num_preprocess_threads: 4
    num_gpus: 4
    moving_average_decay: 0.9999
    learning_rate:
        initial: 0.1
        decay_factor: 0.16
        num_epochs_per_decay: 30.0
    optimizer:
        type: tensorflow.train.RMSPropOptimizer
        decay: 0.9
        momentum: 0.9
        epsilon: 1.0
