---
train:
    learning_rate:
        type: tensorflow.train.exponential_decay
        _initial: 0.1
        _num_epochs_per_decay: 30
        _default_batch_size: 128
        decay_rate: 0.16
        learning_rate: !arith >
            $(train.learning_rate._initial) * math.sqrt(
                $(system.batch_size) /
                $(train.learning_rate._default_batch_size))
        decay_steps: !arith >
            $(dataset.num_examples_per_epoch.train) / $(system.batch_size) *
            $(train.learning_rate._num_epochs_per_decay)
        staircase: true
