---
system:
    use_pdb: true
    log_level:
        mayo: info
        tensorflow: 2
    num_gpus: 1
    num_preprocess_threads: 8
    batch_size: 128
    max_steps: 10000000
    search_paths:
        datasets: [datasets]
        checkpoints: [checkpoints]
        summaries: [summaries]
    checkpoint:
        load: latest
        save: true
