---
system:
    num_gpus: 1
    visible_gpus: auto
    preprocess:
        num_readers: 4
        num_threads: 8
    batch_size: 128
    max_epochs: null
    pdb:
        use: true
        skip:
            - KeyboardInterrupt
            - FileNotFoundError
    log:
        level: info
        frame: false
        tensorflow: 2
        metrics_history_count: 200
    search_path:
        dataset:
            - datasets/
        checkpoint:
            save: &cp_paths
                - checkpoints/$(model.name)/$(dataset.name)/
            load: *cp_paths
        summary:
            - summaries/$(model.name)/$(dataset.name)/
    checkpoint:
        load: latest
        save: {interval: 1, countdown: 3}
    summary: {save: true}
