---
system:
    use_pdb: true
    log_level:
        mayo: info
        tensorflow: 2
    num_gpus: 1
    num_preprocess_threads: 8
    batch_size: 128
    max_epochs: 90
    search_paths:
        datasets:
            - datasets
        checkpoints:
            save: &cp_paths
                - checkpoints/$(name)/$(dataset.name)
            load: *cp_paths
        summaries:
            - summaries/$(name)/$(dataset.name)
    checkpoint:
        load: latest
        save: true
    save_summary: true
    metrics_history_count: 200
