---
system:
    use_pdb: true
    num_gpus: 4
    num_preprocess_threads: 4
    batch_size: 64
    max_steps: 10000000
    tensorflow_log_level: 2
    search_paths:
        datasets: [datasets]
        checkpoints: [checkpoints]
        summaries: [summaries]
